/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SingSongIdImport } from './routes/sing/$songId'

// Create Virtual Routes

const TestLazyImport = createFileRoute('/test')()
const SongsLazyImport = createFileRoute('/songs')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TestLazyRoute = TestLazyImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/test.lazy').then((d) => d.Route))

const SongsLazyRoute = SongsLazyImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/songs.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SingSongIdRoute = SingSongIdImport.update({
  id: '/sing/$songId',
  path: '/sing/$songId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsLazyImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestLazyImport
      parentRoute: typeof rootRoute
    }
    '/sing/$songId': {
      id: '/sing/$songId'
      path: '/sing/$songId'
      fullPath: '/sing/$songId'
      preLoaderRoute: typeof SingSongIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/songs': typeof SongsLazyRoute
  '/test': typeof TestLazyRoute
  '/sing/$songId': typeof SingSongIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/songs': typeof SongsLazyRoute
  '/test': typeof TestLazyRoute
  '/sing/$songId': typeof SingSongIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/songs': typeof SongsLazyRoute
  '/test': typeof TestLazyRoute
  '/sing/$songId': typeof SingSongIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/songs' | '/test' | '/sing/$songId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/songs' | '/test' | '/sing/$songId'
  id: '__root__' | '/' | '/about' | '/songs' | '/test' | '/sing/$songId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  SongsLazyRoute: typeof SongsLazyRoute
  TestLazyRoute: typeof TestLazyRoute
  SingSongIdRoute: typeof SingSongIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  SongsLazyRoute: SongsLazyRoute,
  TestLazyRoute: TestLazyRoute,
  SingSongIdRoute: SingSongIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/songs",
        "/test",
        "/sing/$songId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/songs": {
      "filePath": "songs.lazy.tsx"
    },
    "/test": {
      "filePath": "test.lazy.tsx"
    },
    "/sing/$songId": {
      "filePath": "sing/$songId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
